<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <AnalysisLevel>preview</AnalysisLevel>
        <ImplicitUsings>enable</ImplicitUsings>
        <TargetFramework>net10.0</TargetFramework>
        <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
        <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.10" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Blazouter.WebAssembly\Blazouter.WebAssembly.csproj" />
        <ProjectReference Include="..\Blazouter.LazyModule.Sample\Blazouter.LazyModule.Sample.csproj" />
    </ItemGroup>

    <ItemGroup>
        <BlazorWebAssemblyLazyLoad Include="Blazouter.LazyModule.Sample.wasm" />
    </ItemGroup>

    <ItemGroup>
        <None Include="bun.lock" Visible="false" />
        <None Include="package.json" Visible="false" />
        <None Include="Tailwind.txt" Visible="false" />
        <None Include="postcss.config.mjs" Visible="false" />
        <None Include="tailwind.config.js" Visible="false" />
    </ItemGroup>

</Project>