name: CI Build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Build
    runs-on: windows-2022
    permissions:
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        configuration: [
            Release
        ]
        solution: [
            Blazouter.sln
        ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
        dotnet-quality: preview

    - name: Restore .NET workloads
      run: dotnet workload restore

    - name: Restore the Blazouter
      run: dotnet restore ${{ matrix.solution }} -p:Configuration=${{ matrix.configuration }} -p:UseSharedCompilation=false --configfile ./NuGet.Config

    - name: Clean the Blazouter
      run: dotnet clean ${{ matrix.solution }}

    - name: Build the Blazouter
      run: dotnet build ${{ matrix.solution }} -c ${{ matrix.configuration }} -p:UseSharedCompilation=false --no-restore /nowarn:CS0067,CS0108,CS0109,CS0114,CS0169,CS0414,CS0618,CS0649,CS8632,CA1416,NU5104,NETSDK1138,SYSLIB0003