<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <AnalysisLevel>preview</AnalysisLevel>
        <ImplicitUsings>enable</ImplicitUsings>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Blazouter\Blazouter.csproj" />
    </ItemGroup>

</Project>